### PR TITLE
Add back RTCInsertableStreams which was removed by error in PR62

### PR DESCRIPTION
**Pull request by youennf**
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/webrtc-insertable-streams/pull/73.html" title="Last updated on Mar 8, 2021, 10:07 AM UTC (d49e2a9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-insertable-streams/73/45d6fb6...youennf:d49e2a9.html" title="Last updated on Mar 8, 2021, 10:07 AM UTC (d49e2a9)">Diff</a>

### CODE REVIEW

**Comment by youennf** [comment]
Fixes https://github.com/w3c/webrtc-insertable-streams/issues/72

**Comment by foolip** [comment]
Thanks @youennf!

**Comment by youennf** [comment]
@dontcallmedom, 'make' did not catch this missing reference.
Is there a way to catch this error from existing tools? If so, could it be added to the bots processing PRs?

**Comment by dontcallmedom** [comment]
#74 will configure the bot to detect that kind of error, although the [bot itself has bug at the moment](https://github.com/w3c/spec-prod/issues/20#issuecomment-792666167); SFrameTransportOptions seems to be also missing (and thus will make the build fail once the bot is correctly set up)

**Comment by youennf** [comment]
> #74 will configure the bot to detect that kind of error, although the [bot itself has bug at the moment](https://github.com/w3c/spec-prod/issues/20#issuecomment-792666167); SFrameTransportOptions seems to be also missing (and thus will make the build fail once the bot is correctly set up)

Thanks!
Fixing SFrameTransportOptions typo at https://github.com/w3c/webrtc-insertable-streams/pull/75

**Review by jan-ivar — APPROVED** [review]

**Pull request merged**
